import type { MaritimeProviderDefinition } from "./maritime-contracts";

export const MARITIME_PROVIDERS: MaritimeProviderDefinition[] = [
  {
    id: "OPENWATERS",
    label: "Open Waters / aiscast",
    kind: "AIS",
    access: "FREE",
    liveCapable: true,
    enabledByDefault: false,
    endpoint: "https://ais.openwaters.io/v1/vessels",
    note: "Free read API with GeoJSON snapshot, WebSocket and SSE streams; collector remains OFF.",
  },
  {
    id: "AISSTREAM",
    label: "AISStream",
    kind: "AIS",
    access: "FREE_TOKEN",
    liveCapable: true,
    enabledByDefault: false,
    endpoint: "wss://stream.aisstream.io/v0/stream",
    note: "Free global AIS WebSocket; requires user token when activated.",
  },
  {
    id: "AIS_CATCHER",
    label: "AIS-catcher Community",
    kind: "AIS",
    access: "FREE",
    liveCapable: true,
    enabledByDefault: false,
    note: "Community receiver ecosystem for live AIS coverage and station quality context.",
  },
  {
    id: "VESSELFINDER",
    label: "VesselFinder",
    kind: "AIS",
    access: "PAID_API",
    liveCapable: true,
    enabledByDefault: false,
    endpoint: "https://api.vesselfinder.com/",
    note: "Official API adapter slot; credentials never stored in source code.",
  },
  {
    id: "TANKERTRACKERS",
    label: "TankerTrackers",
    kind: "TANKER",
    access: "PUBLIC_OSINT",
    liveCapable: false,
    enabledByDefault: false,
    note: "OSINT enrichment slot for tanker, voyage, STS and satellite observations; no scraping or bypass.",
  },
  {
    id: "GLOBAL_FISHING_WATCH",
    label: "Global Fishing Watch",
    kind: "FISHING",
    access: "PUBLIC_OSINT",
    liveCapable: true,
    enabledByDefault: false,
    note: "Vessel presence, encounters, port visits and fishing activity enrichment slot.",
  },
  {
    id: "OPENSKY",
    label: "OpenSky Network",
    kind: "AIR",
    access: "FREE",
    liveCapable: true,
    enabledByDefault: false,
    note: "ADS-B aircraft source kept separate from maritime collectors.",
  },
  {
    id: "FLIGHTRADAR24",
    label: "Flightradar24",
    kind: "AIR",
    access: "PAID_API",
    liveCapable: true,
    enabledByDefault: false,
    endpoint: "https://www.flightradar24.com/",
    note: "Official API adapter slot; no website scraping or access-control bypass.",
  },
];

export const MARITIME_WIRE_STATUS = MARITIME_PROVIDERS.map((provider) => ({
  component: provider.label,
  status: "POWERED_OFF" as const,
  note: provider.note,
}));
