import type { MaritimeProvider, MaritimeSourceKind } from "./maritime-contracts";

export const MARITIME_PROVIDERS: MaritimeProvider[] = [
  {
    id: "AISSTREAM",
    label: "AISStream",
    role: "Primary live AIS stream",
    scope: "Global terrestrial AIS",
    liveAvailable: true,
    requiresKey: true,
    notes: "Free WebSocket feed with bounding-box subscriptions; best near coastal receiver coverage.",
  },
  {
    id: "VESSELFINDER",
    label: "VesselFinder",
    role: "AIS + vessel enrichment",
    scope: "Global",
    liveAvailable: true,
    requiresKey: true,
    notes: "Official LiveData supports area queries plus AIS, voyage, and master datasets.",
  },
  {
    id: "VESSELTRAFFIC_MCP",
    label: "Vessel Traffic MCP",
    role: "Normalized maritime adapter",
    scope: "Global / provider aggregation",
    liveAvailable: true,
    requiresKey: false,
    notes: "Read-only open-source adapter surface with provenance and BYOK provider support.",
  },
  {
    id: "TANKERTRACKERS",
    label: "TankerTrackers",
    role: "Tanker / oil intelligence",
    scope: "Global",
    liveAvailable: true,
    requiresKey: true,
    notes: "Use as enrichment for tanker activity, satellite observations, voyages, and STS intelligence when authorized.",
  },
  {
    id: "SHIPFINDER",
    label: "ShipFinder",
    role: "Public vessel lookup fallback",
    scope: "Global",
    liveAvailable: true,
    requiresKey: false,
    notes: "Public no-login pages have useful vessel identity and position data; provider responses must remain attributed.",
  },
  {
    id: "MYSHIPTRACKING",
    label: "MyShipTracking",
    role: "Public tracking fallback",
    scope: "Global",
    liveAvailable: true,
    requiresKey: false,
    notes: "Keep as an optional public-provider adapter and do not bypass anti-bot controls.",
  },
  {
    id: "MARINETRAFFIC",
    label: "MarineTraffic",
    role: "Commercial AIS enrichment",
    scope: "Global",
    liveAvailable: true,
    requiresKey: true,
    notes: "Authorized API / BYOK only. No public-page capture adapter.",
  },
  {
    id: "FLIGHTRADAR24",
    label: "Flightradar24",
    role: "Live aircraft feed",
    scope: "Global",
    liveAvailable: true,
    requiresKey: true,
    notes: "Official API supports real-time flight data; older JSON methods should not be treated as the integration path.",
  },
  {
    id: "OPENSKY",
    label: "OpenSky",
    role: "Aircraft fallback",
    scope: "Global",
    liveAvailable: true,
    requiresKey: false,
    notes: "Optional aircraft fallback for a multi-source aviation layer.",
  },
];

export const MARITIME_SOURCE_ORDER: MaritimeSourceKind[] = MARITIME_PROVIDERS.map((provider) => provider.id);
